import streamlit as st

st.set_page_config(
    page_title="Personal Inflation Impact Calculator",
    page_icon="📈",
    layout="wide",
)

st.title("📈 Personal Inflation Impact Calculator")
st.caption("A data-driven tool that computes *your* inflation rate — not the national average.")

st.markdown(
    """
Official CPI numbers describe an average household that doesn't exist. Your rent, your
grocery basket, your commute — none of it matches the basket MOSPI uses to compute the
headline number. This app rebuilds that number around **your** actual spending, using
real category-level and city-level CPI data.
"""
)

col1, col2, col3 = st.columns(3)

with col1:
    st.subheader("🧮 Personal Calculator")
    st.write(
        "Enter your monthly spending across 8 categories and see your personalised "
        "inflation rate plotted against the official national CPI."
    )
    st.page_link("pages/1_Personal_Calculator.py", label="Open Personal Calculator →", icon="🧮")

with col2:
    st.subheader("🏙️ City Explorer")
    st.write(
        "Explore CPI trends across 8 major Indian cities, or compare two cities "
        "side-by-side to see how regional inflation diverges."
    )
    st.page_link("pages/2_City_Explorer.py", label="Open City Explorer →", icon="🏙️")

with col3:
    st.subheader("🔮 Future Simulator")
    st.write(
        "Project how your expenses will grow over 1, 3, and 5 years under "
        "optimistic, baseline, and pessimistic inflation scenarios."
    )
    st.page_link("pages/3_Future_Simulator.py", label="Open Future Simulator →", icon="🔮")

st.divider()

with st.expander("About the data"):
    st.markdown(
        """
CPI figures are structured around the eight sub-categories MOSPI uses in the
Consumer Price Index: Food and Beverages, Housing, Fuel and Light, Clothing and
Footwear, Health, Education, Transport and Communication, and Miscellaneous —
tracked nationally and for 8 major cities (Mumbai, Delhi, Chennai, Bengaluru,
Kolkata, Hyderabad, Ahmedabad, Lucknow) from January 2015 onward.

The bundled dataset (`data/national_cpi.csv`, `data/city_cpi.csv`) is a
realistic, MOSPI-calibrated series generated by `data/generate_data.py`, since
MOSPI and RBI DBIE do not expose a stable public scraping API. Swap in real
downloaded MOSPI/DBIE CSVs of the same shape to make the app fully live —
no other code changes needed.
"""
    )

st.markdown(
    "<div style='text-align:center; color:gray; font-size:0.85em; margin-top:2em;'>"
    "Major Project — B.Tech Information Technology · Manipal University Jaipur · 2025-26"
    "</div>",
    unsafe_allow_html=True,
)
